### ISSUE TITLE
show player mode in potrait rather than Landscape

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#110]
@lental @jpdutoit @jonslenkooyala @pilievOoyala @seanatooyala 
Pls provide solution for this .
We uploaded a video in Portrait mode in Dashboard while we run the app the video  plays in Landscape mode.
Attaching the screenshot for reference.
![screen shot 2016-06-15 at 2 46 48 pm](https://cloud.githubusercontent.com/assets/19282172/16074437/1a797c36-3308-11e6-94ee-86670688818e.png)

 Can we play portrait video without having that black background

**Comment by santhoshrajs** [comment]
Its one of our requirement .help me to move forward.Thanks in Advance.

**Comment by santhoshrajs** [comment]
@lental 
No one gave solution till now for this solution.

**Comment by lental** [comment]
Github is not a place to ask implementation questions - Please talk to Technical Support for information.  If you find issues with our Sample applications, you can file bugs here.
