### ISSUE TITLE
OOVASTAd Bitcode Error

### ISSUE THREAD

**Issue by dmorrow** [ooyala/ios-sample-apps#117]
Using OoyalaSDK (4.15.1) installed with CocoaPods in a Swift project, we get the following error when compiling for the App Store

ld: bitcode bundle could not be generated because '/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTAd.o)' was built without full bitcode.

**Comment by lental** [comment]
hmm it looks like our enabling of bitcode isn't enough.  I'm going to try out the steps here: https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9#.ybb837pjg

**Comment by dmorrow** [comment]
Thanks @lental.  Any ETA when you can push this fix?  We were hoping to submit to the app store tomorrow, and of course only came across this issue once we started using bitcode enabled builds to submit.

**Comment by lental** [comment]
so my answer is - honestly we're not sure. Thanks for bringing it up, and I'll do what I can to resolve the issue. However, it's more complicated than just following those steps. We need to do some changes to support the suggestions up there, and when that works then I'll update you here

**Comment by lental** [comment]
By the way - we should have fixed this in the upcoming release, 4.16.0, which should be dropping sometime this week.  stay tuned!

**Comment by lental** [comment]
This should be fixed in the 'stable' branch now, and released with 4.16.0.  Thanks for the report
