### ISSUE TITLE
play video inside uicollection view cell

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#121]
@lental 
I am not able to play ooyala player video inside uicollection view cell.
Could  any one suggest how to implement it.

**Comment by lental** [comment]
Do you know why, specifically, you are not able to play video?  What happens?  

OoyalaPlayer acts like any old view.  It should behave like any view, or specifically any view with an AVPlayer inside it.  We don't provide any particular implementation guidance for any specific use case

If you were able to isolate the issue to the BasicPlaybackSampleApp, you can then escalate the issue through Technical Support.  However, we cannot help you unless you can pinpoint why OoyalaPlayer is specifically not working

**Comment by lental** [comment]
closing the issue.  if there is an issue with the ooyalaplayer, please raise it with Technical Support, after isolating to one of our sample apps.

Thanks,
Mike
