### ISSUE TITLE
how to show and hide the audio icon in ooyala

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#123]
@lental 
I have tried all possible steps but not able to add the audio icon in the ooyala player.and i need to remove progress bar from the player.

**Comment by lental** [comment]
In the Skin SDK (the new Alice UI), or the Old UI?  In Inline, or Fullscreen?

**Comment by brol1dev** [comment]
@santhoshrajs, let us know if we can help you further here. Is this related to #124?

**Comment by lental** [comment]
closing, please reopen if you have more details about t he requirements
