### ISSUE TITLE
unable to play audio in ooyal skin player view controller

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#125]
if i give video embeded code i am able to play video in ooyala skin player view controller but if i give audio embeded code i am unable to play audio in this player.

Kindly help me what needs to be done

**Comment by Matthew-C** [comment]
Can you please provide an embedcode?

Matthew

**Comment by santhoshrajs** [comment]
@Matthew-C 
embeded code:JxaHE0NTE6dOyJDTNy48wtKySRUJubEG

**Comment by santhoshrajs** [comment]
@Matthew-C

Any updates?
Why i  am unable to play audio in ooyala skin player view controller.

**Comment by lental** [comment]
@santhoshrajs, I've had to ask you multiple times, but please escalate issues with the player through Technical Support. We will not triage customer-specific issues through the github issues.  If you have technical issues around compiling or running the sample applications as they are provided, you can escalate those tickets here (like the iOS7 crash you raised earlier). However, questions about functionality and issues with your configuration, you will need to raise with Technical Support or your CSM.  

I hope you understand my reasoning, we have a technical  support team for this very reason, to help debug issues, and bypassing that channel negatively impacts our ability to  support customers as a whole.

Closing this ticket. Thanks
