### ISSUE TITLE
ContentProtectionSampleApp crashes when selecting any player selection option 

### ISSUE THREAD

**Issue by chrisl777** [ooyala/ios-sample-apps#131]
-Build and run the app from the ContentProtectionSampleApp project. 
-Tap on any of the player selection options presented at the beginning. 

Expected
The selected player option should load. 

Actual 
The app crashes.

**Comment by lental** [comment]
Yeah, "Content Protection Sample App" is admittedly not well explained.  None of the assets will play without an API Key and Secret, which we don't put in the application (We may consider putting our key and secret in here, if we generate read-only credentials that would not create a security issue)

I did write up a README that might explain how a developer could apply Content Protection Sample App to their own assets, which would be more useful: https://github.com/ooyala/ios-sample-apps/tree/stable/ContentProtectionSampleApp

I hope this helps

**Comment by chrisl777** [comment]
Perhaps an alert would be a better approach then a crash?

**Comment by chrisl777** [comment]
Thanks for pointing me to the documentation, btw.

**Comment by brol1dev** [comment]
I'm closing this ticket. We see the concern of having an app that crashes instead of guiding the users, we'll be fixing this, thanks for the feedback @chrisl777
