### ISSUE TITLE
ContentProtectionSampleApp is missing Adobe Pass option 

### ISSUE THREAD

**Issue by chrisl777** [ooyala/ios-sample-apps#132]
-Build and run the ContentProtectionSampleApp. 

Expected
Should be able to follow a sample Adobe Pass authentication process. 

Actual 
The Adobe Pass option is not available from the list of player options. This is very unfortunate b/c there isn't clear documentation at http://support.ooyala.com/ about iOS-specific Adobe Pass flow.

**Comment by lental** [comment]
Are you planning on integrating Adobe Pass into your application?  I would talk to your CSM about getting support for that integration.

**Comment by chrisl777** [comment]
Yes, we are integrating with Adobe Pass. We are in touch with our CSM. It's just unfortunate that I can't use the sample app to run through the Adobe-specific code.

**Comment by lental** [comment]
Okay, phew, was able to fix the case without doing too much crazy stuff.

Content Protection Sample App:

To verify Adobe Pass is necessary: 
1. Open AdobePassPlayerViewController, comment out self.passController and the addChildViewController:self.passController lines 60-64
2. Run the ContentProtectionSampleApp, choose "Adobe Pass"
3. press "set Embed Code", note the authorization failure in the logs

To verify Adobe Pass works:
1. Revert the changes from above
2. Run the ContentProtectionSampleApp, choose Adobe Pass
3. press "setEmbedCode", note the MVPD dialog appears.
4. Choose an option (I personally chose Temp 30 min)
5. A white screen appears, and takes upwards of 2 minutes of staring until it is completed.  It takes a while. (I think network to the test server is very slow
6. Screen will disappear, and video will playback.

At a high level, there is an AdobePassViewController which acts as the "EmbedTokenGenerator".  This ViewController ensures AdobePass AuthN is done, and then uses the Adobe Pass Token to create an OPT that Ooyala's servers can consume

I appreciate your patience.  Good luck with the integration!

Note: if you want android as well, file a ticket on android sample apps and we'll do the same exercise there
