### ISSUE TITLE
Skin Player - Accessibility

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#147]
Hi @lental 
I have integrated skin Player in my application.if i tap play button in player it sounds "G",If i tap closed caption it sounds as "k".

How can i change these names from application perspective

**Comment by lental** [comment]
You would need to file a feature request with the CSM/Technical Support.  It sounds like there is work that needs to be done around accessibility with our UI.

Thanks,
Mike
