### ISSUE TITLE
App Transport Security in iOS

### ISSUE THREAD

**Issue by kmuralidharan91** [ooyala/ios-sample-apps#154]
My enterprise iOS app is using Ooyala SDK to render Ooyala videos in Ooyala player. According to apple documentation, we changed all our web requests to https from http but we noted from Charles Proxy that only Ooyala is hitting http.

How to overcome this ?
**I want to hit only https from my app.**

**Comment by lental** [comment]
please don't mass-mention people.  the correct users will join the conversation when necessary.

Do you have a CSM?  These conversations will need to go either through your CSM or through Technical Support. What specific requests are going through HTTP?  When you talk to your CSM or TS, please provide a charles log file that has all of the problematic requests, so they can all be resolved in one go.  

Are you using the latest versions of Ooyala SDK? Some API requests will only start using HTTPS with 4.20.0 and above

**Comment by lental** [comment]
We have a process with Technical Support to work with each customer around ATS support.  Please contact them with all of the information in my previous comment.

Thanks,
Mike
