### ISSUE TITLE
Don't show icon play, pause, volume, .... on OOyalaplayer in Swift 3.0.1

### ISSUE THREAD

**Issue by quyetts** [ooyala/ios-sample-apps#163]
![simulator screen shot mar 9 2017 11 14 36](https://cloud.githubusercontent.com/assets/12297856/23735718/f00726f4-04b9-11e7-9e8c-33d4bf26cc0b.png)

**Comment by quyetts** [comment]
plz help me!
Thank all!

**Comment by lental** [comment]
This usually means that you did not add the font to your application's bundle and info.plist.  Check out the second bullet from this doc:

https://github.com/ooyala/native-skin/blob/stable/dev_docs/README-ios.md#how-to-update-an-existing-application-with-the-ios-skin

**Comment by lental** [comment]
closing as I think my answer solves the problem. Please reopen if it is still a problem
