### ISSUE TITLE
Notification for fullscreen/inline video

### ISSUE THREAD

**Issue by shafqat-muneer** [ooyala/ios-sample-apps#195]
Hi,
I want to get notify in my app when Ooyala Player goes fullscreen and when come back to inline. Can it be possible in existing ooyala player implementation?
If yes, then please guide me.

Thanks,
Shafqat

**Comment by maxkupetskii** [comment]
As for now we have 2 `NSNotification` for this events:
```
OOOoyalaPlayerViewControllerFullscreenEnter
OOOoyalaPlayerViewControllerFullscreenExit
```
If you subscribe to them you'll receive corresponding events.

Closing this ticket as resolved
