### ISSUE TITLE
CompleteSampleApp doesn't compile

### ISSUE THREAD

**Issue by acorscadden** [ooyala/ios-sample-apps#24]
It looks like it's missing a bunch of libraries.
http://i.imgur.com/IoiMop4.png

**Comment by jonslenkooyala** [comment]
Thank you for the report. We will be investigating.

**Comment by alexideanova** [comment]
also the sub project won't compile
http://s23.postimg.org/vu5fshmrf/Screen_Shot_2015_09_23_at_20_14_47.png

**Comment by jonslenkooyala** [comment]
Re: AppleWatchSampleApp, thanks for the report. We'll be checking into it.

**Comment by lental** [comment]
CompleteSampleApp should be compilable now. will keep this open for the AppleWatchSampleApp

**Comment by lental** [comment]
fixed Apple Watch Sample App errors in #34

**Comment by acorscadden** [comment]
:+1:

**Comment by lental** [comment]
Thanks, closing now
