### ISSUE TITLE
can not include Ooyala framework in application that also uses libWViPhoneAPI.a

### ISSUE THREAD

**Issue by tbrannam** [ooyala/ios-sample-apps#28]
It appears that the OoyalaSDK.framework/OoyalaSDK is statically linked directly with libWViPhoneAPI.a -- which prevents me from using other SDK's which also use this library - is it possible for your framework to require this library to be linked by the application as a dependency instead of performing a static link to it? 

As things stand - I get link error due to a duplicate set of symbols from two different frameworks that both are trying to use libWViPhoneAPI.a

**Comment by jonslenkooyala** [comment]
Thank you for your report. I see what you mean, and we'll address this as soon as we can.

**Comment by lental** [comment]
this should be fixed - Ooyala Framework no longer contains libWViPhoneAPI
