### ISSUE TITLE
Swift doesn't work with the newest sdk

### ISSUE THREAD

**Issue by dominrleon** [ooyala/ios-sample-apps#350]
When I try to update my SDK compilation to the newest one (4.2.1) it doesn't work. I've even tried swiftsampleapp or ControlsLockScreenSampleApp and when i try to play an asset it makes an uncaught exception. Is it working ok for anyone?

**Comment by maxkupetskii** [comment]
@dominrleon 
I see that `ControlsLockScreenSampleApp` has a Swift version of 4.2 and it works without any errors.

Could you please describe an issue you have?
