### ISSUE TITLE
Crashes when restart download after terminate the app with active, not finished download

### ISSUE THREAD

**Issue by IgnSergey** [ooyala/ios-sample-apps#356]
Steps to reproduce:
1. run DownloadToOwnSampleApp
2. start downloading an asset(for example: HLS Clear)
3. waiting until progress will be in range 1 ... 99. for example 5%
4. close the app.
5. run DownloadToOwnSampleApp - app crashes with reason: 
<img width="1141" alt="screen shot 2019-02-12 at 11 30 57" src="https://user-images.githubusercontent.com/40299304/52625466-bad72480-2eb9-11e9-9c62-b57bd5c8fb0f.png">

Tested on SDK 4.40, 4.41, 4.43.0_RC15

**Comment by maxkupetskii** [comment]
Will be fixed in 4.43 release and also in next candidate (RC18 or RC19)
