### ISSUE TITLE
Downloaded asset + active Airplay = crash

### ISSUE THREAD

**Issue by IgnSergey** [ooyala/ios-sample-apps#405]
Hello.
In our app(iOS) we can download assets(FPS), and when user starts(turns on Airplay during) watching downloaded assets with active Airplay the OOyalaSDK crashes. That's why I have two questions. 
1. Is it possible to play downloaded encrypted assets via Airplay? Or this possibility is not support. What about future, will be or not?
2. Can player returns some error instead of crash?
PS. sample app also crashes when trying to play downloaded FPS asset, non-encrypted streams are works normally. reproduced 100%.

**Comment by maxkupetskii** [comment]
@IgnSergey 

Could you please provide more details?
I've retested with 4.46 GA and I wasn't able to get a crash.
However, I do believe that playing Fariplay asset via AirPlay in mirroring mode is not supported: the video won't show, only sound. You can refer it here https://developer.apple.com/videos/play/wwdc2015/502/

**Comment by IgnSergey** [comment]
Hello.
Just configure your sample app(API_KEY, API_SECRET, pcode, embedCode, domain). Download asset. Start watching **downloaded** asset. Turn on airplay from system menu. App crashes. Ooyala SDK Version: v4.46.0_RC14
<img width="1440" alt="Screen Shot 2019-07-01 at 09 24 13" src="https://user-images.githubusercontent.com/40299304/60415614-50165380-9be4-11e9-8d02-463cab7a3dca.png">
[crash.docx](https://github.com/ooyala/ios-sample-apps/files/3344211/crash.docx)
[crash.pdf](https://github.com/ooyala/ios-sample-apps/files/3344202/crash.pdf)

**Comment by maxkupetskii** [comment]
@IgnSergey 

I've used one of ours FP assets:
```PlayerSelectionOption(pcode: "x0b2cyOupu0FFK5hCr4zXg8KKcrm",
                            embedCode: "cycDhnMzE66D5DPpy3oIOzli1HVMoYnJ",
                            title: "HLS Fairplay (unconfigured)",
                            domain: OOPlayerDomain(string: "https://www.ooyala.com"),
                            embedTokenGenerator: BasicEmbedTokenGenerator(pcode: "x0b2cyOupu0FFK5hCr4zXg8KKcrm",
                                                                          apiKey: "x0b2cyOupu0FFK5hCr4zXg8KKcrm.-s6jH",
                                                                          apiSecret: "ZCMQt2CCVqlHWce6dG5w2WA6fkAM_JaWgoI_yzQp",
                                                                          accountId: "106219",
                                                                          authorizeHost: "https://www.ooyala.com")),```
Downloaded, started playing offline, then from control center I enable mirroring via AirPlay -- and I don't get a crash.
4.46RC14

**Comment by maxkupetskii** [comment]
@IgnSergey 

I've made a short video with my steps: [HLS Fairplay + DTO + AirPlay](https://epam-my.sharepoint.com/:v:/p/maksim_kupetskii/Ef62nXnH_WpMs7-V9MsYq7oBz-naXED-V0ZLV_qxeYvfHA?e=8gS2me)

**Comment by IgnSergey** [comment]
Enable Airplay streaming not screen mirroring via Airplay. 
Short video with my steps: https://drive.google.com/file/d/1UWehIis1TjDvfmf_oxuRBH_uPMNBHO4z/view?usp=sharing

**Comment by maxkupetskii** [comment]
@IgnSergey 

Finally, I was able to reproduce, thanks
Will check now

**Comment by maxkupetskii** [comment]
@IgnSergey 

The fix will be included in 4.47 release

**Comment by loginov-rocks** [comment]
#407

**Comment by loginov-rocks** [comment]
@IgnSergey please reopen if found 4.47 not resolving the issue, thanks!
