### ISSUE TITLE
update SDK 4.40 -> 4.46 issue(question) related to downloaded assets.

### ISSUE THREAD

**Issue by IgnSergey** [ooyala/ios-sample-apps#410]
Hello. Could you help me with SDK update. Our app uses SDK 4.40 and now we want to add some features, one of them is related to audio playback. we want to update to SDK 4.46. And I  have discovered that I can't see and play all the assets that were downloaded with SDK 4.40. Is it ok? Any suggestions? 
Thanks.

**Comment by maxkupetskii** [comment]
@IgnSergey 

We have updated our offline feature and now it uses a much better approach.
Please, refer to :
https://github.com/ooyala/ios-sample-apps/tree/stable/PlaybackLab/DownloadToOwnSampleApp
https://github.com/ooyala/ios-sample-apps/tree/stable/PlaybackLab/DownloadToOwnSampleAppSwift

**Comment by IgnSergey** [comment]
Sure. 
I'm already implemented SDK 4.46 and can download assets - with this no problem. All works properly. 
But question in next: in app with SDK 4.40 I downloaded asset A. After update SDK to 4.46 I can't play it, I have to repeat download. Is it possible to "reuse" downloaded(via SDK 4.40) asset A with SDK 4.46 or this is impossible?
Sorry for disturbing you often.

**Comment by maxkupetskii** [comment]
@IgnSergey 

I'm afraid that's not possible: we changed the way where and how all downloaded assets and FairPlay keys are stored.
