### ISSUE TITLE
Help me to run application)

### ISSUE THREAD

**Issue by Alexsmile2010** [ooyala/ios-sample-apps#423]
Hi! When I run BasicPlaybackSampleApp I received a lot of errors

`ld: warning: ignoring file /ios-sample-apps-stable/BasicPlaybackSampleApp/VendorLibraries/OoyalaSDK.framework/OoyalaSDK, file was built for unsupported file format ( 0x76 0x65 0x72 0x73 0x69 0x6F 0x6E 0x20 0x68 0x74 0x74 0x70 0x73 0x3A 0x2F 0x2F ) which is not the architecture being linked (i386): /Users/alexeyzayakin/Downloads/ios-sample-apps-stable/BasicPlaybackSampleApp/VendorLibraries/OoyalaSDK.framework/OoyalaSDK
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_OOOoyalaPlayerStateConverter", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OOPlayerDomain", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OOOptions", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OODefaultPlayerInfo", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OODefaultAudioOnlyPlayerInfo", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OOOoyalaPlayerTimeChangedNotification", referenced from:
      -[BasicSimplePlayerViewController notificationHandler:] in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OOOoyalaPlayer", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OOOoyalaPlayerViewController", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
  "_OBJC_CLASS_$_OOStreamPlayer", referenced from:
      objc-class-ref in BasicSimplePlayerViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

XCode 10.3
Development target 11.0
Run on simulator

What I need to do for run it and where can I find Pulse.framework?

**Comment by maxkupetskii** [comment]
https://github.com/ooyala/ios-sample-apps/issues/372
