### ISSUE TITLE
isShowingControls

### ISSUE THREAD

**Issue by JuanjoArreola** [ooyala/ios-sample-apps#68]
I have a swift project and I have been struggling for some time trying to find out if the OOOoyalaPlayerViewController is showing the controls (seek, play, pause buttons), I'm not sure if I'm doing something wrong, I already try the properties of OOOoyalaPlayerViewController and OOOoyalaPlayer and the closest I found is getControls which doesn't actually tell me if the controls are showing; if there is an easy way to know this, I would appreciate if you could tell me how, since I couldn't find it nowhere in the docs, thanks.

**Comment by jonslenkooyala** [comment]
Thanks for your question. This appears to not be readily available at the moment. We will look into making that state available.

**Comment by JuanjoArreola** [comment]
Ok, thanks.

**Comment by Matthew-C** [comment]
maybe you can try OOooyalaPlayerViewController.getControls.isVisible

**Comment by jonslenkooyala** [comment]
I think that code path is Internal.

**Comment by brol1dev** [comment]
@JuanjoArreola, do you still have this problem? Please respond to keep this ticket alive.

**Comment by brol1dev** [comment]
Closing the ticket.
