### ISSUE TITLE
OoyalaSDK-iOS compiler error: Cannot import OOAdsLearnMoreButton.h

### ISSUE THREAD

**Issue by benasher44** [ooyala/ios-sample-apps#69]
Importing this header causes a build error trying to import OOAdMoviePlayer.h, which is not included in the public headers of Ooyala.framework. There are 2, maybe 3 options here:
1. Remove OOAdsLearnMoreButton.h from the Ooyala.framework Headers folder. Because this requires having access to a private header, maybe this is supposed to be private?
2. Add OOAdMoviePlayer.h to the Ooyala.framework Headers folder. If OOAdsLearnMoreButton.h is supposed to be public, then clients of this framework need access to OOAdMoviePlayer.h in order to use OOAdsLearnMoreButton.h.
3. Instead of importing OOAdMoviePlayer.h in OOAdsLearnMoreButton.h, declare `OOAdMoviePlayer` as a forward declaration with `@class` instead. This is less ideal, since it would still be the case that nobody can use OOAdsLearnMoreButton, but this way there would be no compiler error.

Given that OOAdMoviePlayer is documented [here](https://apidocs.ooyala.com/ios_mobilesdk/class_o_o_ad_movie_player.html), it seems like the original intention was for OOAdMoviePlayer to be public, in which case 2 would be the best option.

**Comment by jonslenkooyala** [comment]
Thank you for the report! We will work on this.

**Comment by benasher44** [comment]
Thanks! Looking forward to the update!

**Comment by jonslenkooyala** [comment]
@benasher44, what is your particular use case? Thanks.

**Comment by benasher44** [comment]
@jonslenkooyala I'm generating a bridging header to make files available to swift. I'm doing this by compiling all of the publicly available headers in our project into one large bridging header. This header is in the list of public headers for this framework, but it cannot be imported. This seems like a bug.

**Comment by jonslenkooyala** [comment]
@benasher44 I don't mean to imply that I might entirely disagree with your analysis :-) just trying to see if/what gaps there are in the process.

**Comment by benasher44** [comment]
@jonslenkooyala ah sorry. "This seems like a bug." might have been a bit too firm at the end there :). Basically, we don't use this header explicitly, but having this header be publicly available but unusable makes it difficult to generate a complete bridging header for swift. That's the long and short of it.

**Comment by lental** [comment]
This will be fixed in the next release.  Will let you know when it's released

Thanks,
Mike

**Comment by benasher44** [comment]
Awesome!! Thanks!

**Comment by lental** [comment]
This should be fixed in 4.11.0.  We made AdMoviePlayer a forward declaration: https://github.com/ooyala/ios-sample-apps/blob/stable/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/Headers/OOAdsLearnMoreButton.h#L9

Thanks,
Mike

**Comment by benasher44** [comment]
Thanks!!
