### ISSUE TITLE
Where did OOOoyalaPlayer.destroy() go?

### ISSUE THREAD

**Issue by dmorrow** [ooyala/ios-sample-apps#71]
We are able to leave the PlayerViewController before the player has started playing and we have no way to tear down the player.  If we catch it at the right time, audio continues playing and the only way to stop it is the force quit the app.
What is the recommended procedure?

**Comment by Matthew-C** [comment]
If all references to the OOOoyalaPlayer was released then dealloc will be called and OOOoyalaPlayer can be properly tear down. You can check the log to see if OOOoyalaPlayer.dealloc is printed out.

**Comment by lental** [comment]
We were under the impression that OOOoyalaPlayer no longer needed the destroy(), and that we fished out all of the OoyalaPlayer leakage issues,   If you have a repro case, with steps to reproduce, which sample app, etc., file a support incident with Ooyala Technical Support to see that resolved.

Thanks,

**Comment by dmorrow** [comment]
We had a over retained reference.  Setting it to weak solved the problem and allowed OOOoyalaPlayer.dealloc to be called
