### ISSUE TITLE
How to access basePlayer from OOOoyalaPlayer

### ISSUE THREAD

**Issue by dmorrow** [ooyala/ios-sample-apps#72]
We get many debug logs like "OOBaseStreamPlayer.m : Buffer Keeping Up, previous state init current state playing", and [this version](OOBaseStreamPlayer.m : Buffer Keeping Up, previous state init current state playing) of OOOoyalaPlayer.h has a reference to OOStreamPlayer *basePlayer;

Is this still accessible in OOOoyalaPlayer, as we would like to subscribe to these events as well.

@lental - we're in a bit of a time crunch.  If you have any ideas, they would be well received.

**Comment by lental** [comment]
we do not expose buffer keeping up states.  We do expose buffering through the STATE_CHANGED events, where it goes from PLAYING, to LOADING, and back to PLAYING, but we do not expose the specific events under the ooyala player

What are you looking to do?

Finally, I would normally say that these types of questions have to go through Technical Support. I will probably direct you there for any further questions

**Comment by dmorrow** [comment]
thank you for your very quick response.  however, we noticed there can be a lag between playing and actual video frames appearing, which is why we were looking for an alternative.

**Comment by brol1dev** [comment]
I guess this was resolved through TS. Pinging to let you respond before we close the issue, in case there's still a conversation opened.

Closing tomorrow if no one replies.

**Comment by brol1dev** [comment]
Closing the ticket.
