### ISSUE TITLE
Bitcode support broken

### ISSUE THREAD

**Issue by benasher44** [ooyala/ios-sample-apps#73]
According to the Ooyala release notes, iOS 9 playback is broken with bitcode support enabled. However, the binary that's distributed contains bitcode segments. You can test this by running the following commands:

`otool -arch armv7 -l OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK | grep bitcode`
`otool -arch arm64 -l OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK | grep bitcode`

Are there any plans to fix bitcode support? This is unfortunately keeping us from supporting bitcode in our app.

**Comment by lental** [comment]
bitcode is not supported because one of our dependencies does not have bitcode enabled.  It's unfortunate for us, too.  We plan on removing that dependency within the year - raise the issue with Ooyala Support/your CSM if you want this to gain more traction

**Comment by benasher44** [comment]
@lental will do thanks

**Comment by lental** [comment]
This is fixed in 4.13 - You should be able to change any sample app with "Bitcode Enabled" set to true, and it should work.

Thanks!

**Comment by benasher44** [comment]
Awesome!! Thanks!!
