### ISSUE TITLE
How to Change the Position of the Play Button in IOS

### ISSUE THREAD

**Issue by santhoshrajs** [ooyala/ios-sample-apps#95]
i am using ooyalaskinsdk  and i need to change the postion of the play and pause button .how can i change the control from our app.

If i change playButtonPosition in start screen its relfecting once i played the video and if i press pause the pause remains in in center not in middle left of the screen.

**Comment by lental** [comment]
This is not something that we support out-of-the-box (as in, as part of skin.json).  If you'd like to see this, you can either raise it to your CSM for request this feature's addition into our SDK, or fork our SDK and try it yourself.  The exact line you would want to change is here: https://github.com/ooyala/native-skin/blob/stable/sdk/react/widgets/VideoViewPlayPause.js#L174

This is not necessarily an issue, therefore I'm going to close this conversation.  If you have any questions, feel free to reopen. However, your request will not get resolved through Github communications.

Thanks,
Mike
